<a href="https://colab.research.google.com/github/ssreddy98-git/BDA-Assignment/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.

1. Reshape the array to 3 by 5

In [ ]:
import numpy as np
import pandas as pd

array = np.random.randint(1,21,size=15)

2. Print array shape.

In [ ]:
array_reshaped = array.reshape(3,5)
print(array_reshaped)

[[13  7  9  4 18]
 [ 8 15 17 16  2]
 [ 7 16  2 20  2]]


3. Replace the max in each row by 0

In [ ]:
row_max = array_reshaped.max(axis=1,keepdims=True)
boolean_mask = array_reshaped == row_max
array_reshaped[boolean_mask] = 0
print(array_reshaped)

[[13  7  9  4  0]
 [ 8 15  0 16  2]
 [ 7 16  2  0  2]]


b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [ ]:
array = np.arange(12,dtype=np.int32).reshape(4,3)
print("array:\n",array)
print("array shape: ",array.shape)
print("array data type: ",array.dtype)

array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array shape:  (4, 3)
array data type:  int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [ ]:
A = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [ ]:
matrix = np.array([[0, 1, 2],
              [3, 4, 5]])

diagonal_sum = np.trace(matrix)

print("Sum of diagonal elements: ", diagonal_sum)

Sum of diagonal elements:  4


e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = A.reshape(2, 3)

print("Original array (3x2): \n", A)
print("\nReshaped array (2x3): \n", B)


Original array (3x2): 
 [[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3): 
 [[1 2 3]
 [4 5 6]]
